### ISSUE TITLE
Bootloop trying to run compiled sketch

### ISSUE THREAD

**Issue by GoremanX** [MichaelThessel/arduino-stoerbert#2]
When the sketch is compiled and uploaded, this is the output from the Serial Monitor:

```VS1053 found
Loaded album from EEPROM: ⸮⸮⸮
Loaded track from EEPROM: 255
Resuming playback
Loading files from directory: /⸮⸮⸮/
File ⸮VS1053 found
Loaded album from EEPROM: ⸮⸮⸮
Loaded track from EEPROM: 255
Resuming playback
Loading files from directory: /⸮⸮⸮/
File ⸮VS1053 found
Loaded album from EEPROM: ⸮⸮⸮
Loaded track from EEPROM: 255
Resuming playback
```
Music never starts playing. It appears to just reboot forever. The 2GB micro SD card is formatted FAT32 and has directories 1 through 9, each one containing files 01.mp3 through 05.mp3. I also tried naming the directories k01 through k09 as specified in readme.MD without success, though the code in player.cpp seems to imply that the directory  naming should actually be 1 through 9 (without k0 in front). The Music Maker shield functions fine and plays music from the same SD card when using the player_simple and player_interrupts example sketches.

**Comment by MichaelThessel** [comment]
Fixed in this commit: 8887e05db1dfca9f5cc15f7338e26f2eef499aae
